// Generated by Wrangler by running `wrangler types`

interface Env {
    NODE_ENV: string
    OAUTH_KV: KVNamespace
    SPECIFICATION_MCP_OAUTH: KVNamespace
    AUTH0_DOMAIN: string
    AUTH0_AUDIENCE: string
    AUTH0_SCOPE: string
    AUTH0_CLIENT_ID: string
    AUTH0_CLIENT_SECRET: string
    DB: D1Database
    MCP_OBJECT: DurableObjectNamespace<import('./src/index-auth0').AuthenticatedSpecificationMCP>
    AI: Ai
}

declare namespace Cloudflare {
    interface Env {
        NODE_ENV: string
        OAUTH_KV: KVNamespace
        SPECIFICATION_MCP_OAUTH: KVNamespace
        AUTH0_DOMAIN: string
        AUTH0_AUDIENCE: string
        AUTH0_SCOPE: string
        AUTH0_CLIENT_ID: string
        AUTH0_CLIENT_SECRET: string
        DB: D1Database
        MCP_OBJECT: DurableObjectNamespace<import('./src/index-auth0').AuthenticatedSpecificationMCP>
        AI: Ai
    }
} 