name = "specification-mcp-server-auth0"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index-auth0-streamable.ts"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "specifications-prod"
database_id = "YOUR_DATABASE_ID"

# KV namespace for OAuth state
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "YOUR_OAUTH_KV_ID"

# Additional KV namespace for MCP OAuth (if needed)
[[kv_namespaces]]
binding = "SPECIFICATION_MCP_OAUTH"
id = "YOUR_MCP_OAUTH_KV_ID"

# Durable Objects binding
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "AuthenticatedSpecificationMCP"

# Durable Object migration - using new_sqlite_classes for free plan
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AuthenticatedSpecificationMCP"]

[vars]
# MCP Server configuration
MCP_SERVER_NAME = "Authenticated Specification Version Control"
MCP_SERVER_VERSION = "1.0.0"

# Environment configuration
NODE_ENV = "production"

# Auth0 configuration (replace with your values)
AUTH0_DOMAIN = "YOUR_TENANT.auth0.com"
AUTH0_CLIENT_ID = "YOUR_CLIENT_ID"
# AUTH0_CLIENT_SECRET should be set via: wrangler secret put AUTH0_CLIENT_SECRET
AUTH0_AUDIENCE = "urn:specification-mcp-server"
AUTH0_SCOPE = "openid email profile offline_access read:specifications write:specifications compare:versions delete:specifications"

# Security: Shorter token lifetimes to force re-authentication
AUTH0_ACCESS_TOKEN_TTL = 900    # 15 minutes instead of default 1 hour
AUTH0_REFRESH_TOKEN_TTL = 3600  # 1 hour instead of default 30 days
AUTH0_FORCE_REAUTH_AFTER = 14400 # 4 hours maximum session